apiVersion: apps/v1
kind: Deployment
metadata:
  name: xds
  labels:
    app: {{ .Chart.Name }}-xds
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-xds
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-xds
    spec:
      containers:
      - name: xds
        image: docker.pkg.github.com/bladedancer/envoyxds/envoyxds:latest_dev
        env:
          - name: XDS_PORT
            value: "12000"
        ports:
        - containerPort: 12000
