// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bladedancer/envoyxds/pkg/authz/authz.proto

package authz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiKeyMessage struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKeyMessage) Reset()         { *m = ApiKeyMessage{} }
func (m *ApiKeyMessage) String() string { return proto.CompactTextString(m) }
func (*ApiKeyMessage) ProtoMessage()    {}
func (*ApiKeyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_799bd7a37f25fa36, []int{0}
}

func (m *ApiKeyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKeyMessage.Unmarshal(m, b)
}
func (m *ApiKeyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKeyMessage.Marshal(b, m, deterministic)
}
func (m *ApiKeyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKeyMessage.Merge(m, src)
}
func (m *ApiKeyMessage) XXX_Size() int {
	return xxx_messageInfo_ApiKeyMessage.Size(m)
}
func (m *ApiKeyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKeyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKeyMessage proto.InternalMessageInfo

func (m *ApiKeyMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiKeyMessage)(nil), "authz.ApiKeyMessage")
}

func init() {
	proto.RegisterFile("bladedancer/envoyxds/pkg/authz/authz.proto", fileDescriptor_799bd7a37f25fa36)
}

var fileDescriptor_799bd7a37f25fa36 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x4a, 0xca, 0x49, 0x4c,
	0x49, 0x4d, 0x49, 0xcc, 0x4b, 0x4e, 0x2d, 0xd2, 0x4f, 0xcd, 0x2b, 0xcb, 0xaf, 0xac, 0x48, 0x29,
	0xd6, 0x2f, 0xc8, 0x4e, 0xd7, 0x4f, 0x2c, 0x2d, 0xc9, 0xa8, 0x82, 0x90, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x22, 0x17, 0xaf, 0x63, 0x41, 0xa6, 0x77, 0x6a, 0xa5,
	0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x99, 0xc4, 0x06, 0xd6, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xed, 0xf5, 0x11, 0x7b, 0x5e, 0x00, 0x00, 0x00,
}
