envoyss:
  fullnameOverride: back
  nameOverride: back
  xdsService:
    address: xds
    port: 9000
  # args:
  #   - -l
  #   - debug
  #   - -c
  #   - /config/envoy.yaml
  secretMounts:
    certs:
      mountPath: /certs
      secretName: default-tls-back
      defaultMode: 511 # TODO
  ports:
    n0:
      containerPort: 443 # probably don't need tls here.
      protocol: TCP
  service:
    name: back
    type: ClusterIP
    ports:
      n0:
        port: 443
        protocol: TCP
  templates:
    envoy.yaml: |-
      admin:
        access_log_path: /dev/stdout
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9901
      node:
        id: shard-0 # TODO: FROM ENV
        cluster: service_xds
      dynamic_resources:
        lds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
              envoy_grpc:
                cluster_name: service_xds
        cds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
              envoy_grpc:
                cluster_name: service_xds
      static_resources:
        clusters:
        - name: service_xds
          connect_timeout: 0.25s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          hosts:
          - socket_address:
              address: {{ .Values.xdsService.address }}
              port_value: {{ .Values.xdsService.port }}
