// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/cache/authz.proto

package cache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeType int32

const (
	ChangeType_UNKNOWN_CTX_TYPE ChangeType = 0
	ChangeType_BASIC            ChangeType = 1
	ChangeType_API              ChangeType = 2
	ChangeType_OAUTH            ChangeType = 3
)

var ChangeType_name = map[int32]string{
	0: "UNKNOWN_CTX_TYPE",
	1: "BASIC",
	2: "API",
	3: "OAUTH",
}

var ChangeType_value = map[string]int32{
	"UNKNOWN_CTX_TYPE": 0,
	"BASIC":            1,
	"API":              2,
	"OAUTH":            3,
}

func (x ChangeType) String() string {
	return proto.EnumName(ChangeType_name, int32(x))
}

func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14b3be27b0a1cc46, []int{0}
}

type AuthEnvelope struct {
	CtxType              ChangeType `protobuf:"varint,1,opt,name=ctxType,proto3,enum=cache.ChangeType" json:"ctxType,omitempty"`
	Context              *any.Any   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthEnvelope) Reset()         { *m = AuthEnvelope{} }
func (m *AuthEnvelope) String() string { return proto.CompactTextString(m) }
func (*AuthEnvelope) ProtoMessage()    {}
func (*AuthEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b3be27b0a1cc46, []int{0}
}

func (m *AuthEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthEnvelope.Unmarshal(m, b)
}
func (m *AuthEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthEnvelope.Marshal(b, m, deterministic)
}
func (m *AuthEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthEnvelope.Merge(m, src)
}
func (m *AuthEnvelope) XXX_Size() int {
	return xxx_messageInfo_AuthEnvelope.Size(m)
}
func (m *AuthEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_AuthEnvelope proto.InternalMessageInfo

func (m *AuthEnvelope) GetCtxType() ChangeType {
	if m != nil {
		return m.CtxType
	}
	return ChangeType_UNKNOWN_CTX_TYPE
}

func (m *AuthEnvelope) GetContext() *any.Any {
	if m != nil {
		return m.Context
	}
	return nil
}

type BasicAuthCtx struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicAuthCtx) Reset()         { *m = BasicAuthCtx{} }
func (m *BasicAuthCtx) String() string { return proto.CompactTextString(m) }
func (*BasicAuthCtx) ProtoMessage()    {}
func (*BasicAuthCtx) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b3be27b0a1cc46, []int{1}
}

func (m *BasicAuthCtx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicAuthCtx.Unmarshal(m, b)
}
func (m *BasicAuthCtx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicAuthCtx.Marshal(b, m, deterministic)
}
func (m *BasicAuthCtx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicAuthCtx.Merge(m, src)
}
func (m *BasicAuthCtx) XXX_Size() int {
	return xxx_messageInfo_BasicAuthCtx.Size(m)
}
func (m *BasicAuthCtx) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicAuthCtx.DiscardUnknown(m)
}

var xxx_messageInfo_BasicAuthCtx proto.InternalMessageInfo

func (m *BasicAuthCtx) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BasicAuthCtx) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type ApiKeyCtx struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKeyCtx) Reset()         { *m = ApiKeyCtx{} }
func (m *ApiKeyCtx) String() string { return proto.CompactTextString(m) }
func (*ApiKeyCtx) ProtoMessage()    {}
func (*ApiKeyCtx) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b3be27b0a1cc46, []int{2}
}

func (m *ApiKeyCtx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKeyCtx.Unmarshal(m, b)
}
func (m *ApiKeyCtx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKeyCtx.Marshal(b, m, deterministic)
}
func (m *ApiKeyCtx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKeyCtx.Merge(m, src)
}
func (m *ApiKeyCtx) XXX_Size() int {
	return xxx_messageInfo_ApiKeyCtx.Size(m)
}
func (m *ApiKeyCtx) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKeyCtx.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKeyCtx proto.InternalMessageInfo

func (m *ApiKeyCtx) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type OAuthCtx struct {
	Oath                 string   `protobuf:"bytes,1,opt,name=oath,proto3" json:"oath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthCtx) Reset()         { *m = OAuthCtx{} }
func (m *OAuthCtx) String() string { return proto.CompactTextString(m) }
func (*OAuthCtx) ProtoMessage()    {}
func (*OAuthCtx) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b3be27b0a1cc46, []int{3}
}

func (m *OAuthCtx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthCtx.Unmarshal(m, b)
}
func (m *OAuthCtx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthCtx.Marshal(b, m, deterministic)
}
func (m *OAuthCtx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthCtx.Merge(m, src)
}
func (m *OAuthCtx) XXX_Size() int {
	return xxx_messageInfo_OAuthCtx.Size(m)
}
func (m *OAuthCtx) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthCtx.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthCtx proto.InternalMessageInfo

func (m *OAuthCtx) GetOath() string {
	if m != nil {
		return m.Oath
	}
	return ""
}

type ApiKeyMessage struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKeyMessage) Reset()         { *m = ApiKeyMessage{} }
func (m *ApiKeyMessage) String() string { return proto.CompactTextString(m) }
func (*ApiKeyMessage) ProtoMessage()    {}
func (*ApiKeyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b3be27b0a1cc46, []int{4}
}

func (m *ApiKeyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKeyMessage.Unmarshal(m, b)
}
func (m *ApiKeyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKeyMessage.Marshal(b, m, deterministic)
}
func (m *ApiKeyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKeyMessage.Merge(m, src)
}
func (m *ApiKeyMessage) XXX_Size() int {
	return xxx_messageInfo_ApiKeyMessage.Size(m)
}
func (m *ApiKeyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKeyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKeyMessage proto.InternalMessageInfo

func (m *ApiKeyMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterEnum("cache.ChangeType", ChangeType_name, ChangeType_value)
	proto.RegisterType((*AuthEnvelope)(nil), "cache.AuthEnvelope")
	proto.RegisterType((*BasicAuthCtx)(nil), "cache.BasicAuthCtx")
	proto.RegisterType((*ApiKeyCtx)(nil), "cache.ApiKeyCtx")
	proto.RegisterType((*OAuthCtx)(nil), "cache.OAuthCtx")
	proto.RegisterType((*ApiKeyMessage)(nil), "cache.ApiKeyMessage")
}

func init() { proto.RegisterFile("pkg/cache/authz.proto", fileDescriptor_14b3be27b0a1cc46) }

var fileDescriptor_14b3be27b0a1cc46 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xd1, 0x4f, 0xf2, 0x30,
	0x14, 0xc5, 0xbf, 0xc1, 0x07, 0xb8, 0x2b, 0x9a, 0xda, 0xa0, 0x41, 0x1f, 0x0c, 0xce, 0x17, 0xa2,
	0x49, 0x97, 0x60, 0xe2, 0x7b, 0x59, 0x48, 0x24, 0x44, 0x20, 0x73, 0x44, 0x7d, 0x22, 0x65, 0xa9,
	0x1b, 0x81, 0xac, 0x0d, 0xed, 0x0c, 0xf3, 0xaf, 0x37, 0xed, 0x98, 0xfa, 0x76, 0xee, 0xb9, 0xe7,
	0xfe, 0x4e, 0x2e, 0x9c, 0xcb, 0x4d, 0xe2, 0xc7, 0x2c, 0x4e, 0xb9, 0xcf, 0x72, 0x9d, 0x7e, 0x11,
	0xb9, 0x13, 0x5a, 0xe0, 0x86, 0xb5, 0xae, 0x2e, 0x13, 0x21, 0x92, 0x2d, 0xf7, 0xad, 0xb9, 0xca,
	0x3f, 0x7c, 0x96, 0x15, 0x65, 0xc2, 0xdb, 0x40, 0x9b, 0xe6, 0x3a, 0x1d, 0x65, 0x9f, 0x7c, 0x2b,
	0x24, 0xc7, 0xf7, 0xd0, 0x8a, 0xf5, 0x3e, 0x2a, 0x24, 0xef, 0x3a, 0x3d, 0xa7, 0x7f, 0x3a, 0x38,
	0x23, 0x96, 0x41, 0x82, 0x94, 0x65, 0x09, 0x37, 0x8b, 0xb0, 0x4a, 0x60, 0x02, 0xad, 0x58, 0x64,
	0x9a, 0xef, 0x75, 0xb7, 0xd6, 0x73, 0xfa, 0xc7, 0x83, 0x0e, 0x29, 0x9b, 0x48, 0xd5, 0x44, 0x68,
	0x56, 0x84, 0x55, 0xc8, 0x7b, 0x84, 0xf6, 0x90, 0xa9, 0x75, 0x6c, 0x1a, 0x03, 0xbd, 0xc7, 0x18,
	0xfe, 0xe7, 0x8a, 0xef, 0x6c, 0x93, 0x1b, 0x5a, 0x6d, 0x3c, 0xc9, 0x94, 0xb2, 0x40, 0x37, 0xb4,
	0xda, 0xbb, 0x05, 0x97, 0xca, 0xf5, 0x84, 0x17, 0xe6, 0xe8, 0x02, 0x9a, 0xcc, 0x0e, 0x87, 0xb3,
	0xc3, 0xe4, 0x5d, 0xc3, 0xd1, 0xec, 0x0f, 0x58, 0x30, 0x9d, 0x56, 0x60, 0xa3, 0xbd, 0x1b, 0x38,
	0x29, 0x21, 0xcf, 0x5c, 0x29, 0x96, 0x70, 0x8c, 0xa0, 0xbe, 0xf9, 0xa1, 0x18, 0x79, 0x47, 0x01,
	0x7e, 0xdf, 0xc4, 0x1d, 0x40, 0x8b, 0xe9, 0x64, 0x3a, 0x7b, 0x9d, 0x2e, 0x83, 0xe8, 0x6d, 0x19,
	0xbd, 0xcf, 0x47, 0xe8, 0x1f, 0x76, 0xa1, 0x31, 0xa4, 0x2f, 0xe3, 0x00, 0x39, 0xb8, 0x05, 0x75,
	0x3a, 0x1f, 0xa3, 0x9a, 0xf1, 0x66, 0x74, 0x11, 0x3d, 0xa1, 0xfa, 0xaa, 0x69, 0x3f, 0x7f, 0xf8,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x0f, 0x70, 0xd8, 0x91, 0x01, 0x00, 0x00,
}
