// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/cache/credential.proto

package cache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Credential struct {
	Credential           map[string]string `protobuf:"bytes,1,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22c9026f73b546, []int{0}
}

func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

func init() {
	proto.RegisterType((*Credential)(nil), "cache.Credential")
	proto.RegisterMapType((map[string]string)(nil), "cache.Credential.CredentialEntry")
}

func init() { proto.RegisterFile("pkg/cache/credential.proto", fileDescriptor_9e22c9026f73b546) }

var fileDescriptor_9e22c9026f73b546 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xc8, 0x4e, 0xd7,
	0x4f, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x4f, 0x2e, 0x4a, 0x4d, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x8b, 0x2b, 0xf5, 0x31, 0x72, 0x71, 0x39,
	0xc3, 0xe5, 0x84, 0x1c, 0xb9, 0xb8, 0x10, 0x2a, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x14,
	0xf5, 0xc0, 0x4a, 0xf5, 0x10, 0xca, 0x90, 0x98, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x48, 0x9a,
	0xa4, 0x6c, 0xb9, 0xf8, 0xd1, 0xa4, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09,
	0x26, 0xb0, 0x18, 0x84, 0x63, 0xc5, 0x64, 0xc1, 0x98, 0xc4, 0x06, 0x76, 0x9e, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x22, 0x41, 0x32, 0x39, 0xbc, 0x00, 0x00, 0x00,
}
