xds:
  xds:
    tenants: 20                   # initial number of tenants
    routes: 10                    # number of APIs per tenant
    pumpInterval: 0               # a new tenant is added every n seconds. Set to 0 to disable.
    domain: bladedancer.dynu.net  # change to your domain
    shards: 3                     # must match replicaCount
    repo: bladedancer                      # Where to pull from
    databaseUrl: postgres://postgres:postgres@saas-postgresql/gateway?sslmode=disable
back:
  envoyss:
    replicaCount: 3 # must match shards
    strategy: |
      type: RollingUpdate

front:
  envoy:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: '*.gm-envoy.moloko.apic-k8s.axwaytest.net.'
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Project=apicentral
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
