xds:
  address: xds
  port: 9000
  tenants: 5
  routes: 10
  pumpInterval: 0
  domain: "bladedancer.dynu.net"

envoy:
  # Have to duplicate these
  xds:
    address: xds
    port: 9000
  # args:
  #   - -l
  #   - trace
  #   - -c
  #   - /config/envoy.yaml
  secretMounts:
    certs:
      mountPath: /certs
      secretName: default-tls
      defaultMode: 511 # TODO
  ports:
    n0:
      containerPort: 443
      protocol: TCP
  service:
    type: LoadBalancer
    ports:
      n0:
        port: 443
        protocol: TCP
    # annotations:
    #   external-dns.alpha.kubernetes.io/hostname: '*.envoy.six.moloko.apic-k8s.axwaytest.net.'
    #   service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Project=apicentral
    #   service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  templates:
    envoy.yaml: |-
      admin:
        access_log_path: /dev/stdout
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9901
      node:
        id: shard-0
        cluster: service_xds
      dynamic_resources:
        lds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
              envoy_grpc:
                cluster_name: service_xds
        cds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
              envoy_grpc:
                cluster_name: service_xds
      static_resources:
        clusters:
        - name: service_xds
          connect_timeout: 0.25s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          upstream_connection_options:
            tcp_keepalive: {}
          hosts:
          - socket_address:
              address: {{ .Values.xds.address }}
              port_value: {{ .Values.xds.port }}
