xds:
  port: 9000

envoy:
    files:
      envoy.yaml: |-
        ## refs:
        ## - https://www.envoyproxy.io/docs/envoy/latest/start/start#quick-start-to-run-simple-example
        ## - https://raw.githubusercontent.com/envoyproxy/envoy/master/configs/google_com_proxy.v2.yaml
        admin:
          access_log_path: /dev/stdout
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 9901

        static_resources:
          listeners:
          - name: listener_0
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 10000
            filter_chains:
            - filters:
              - name: envoy.http_connection_manager
                config:
                  access_log:
                  - name: envoy.file_access_log
                    config:
                      path: /dev/stdout
                  stat_prefix: ingress_http
                  rds:
                    route_config_name: local_route
                    config_source:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          envoy_grpc:
                            cluster_name: service_xds
                  http_filters:
                  - name: envoy.router
          clusters:
          - name: service_xds
            connect_timeout: 0.25s
            type: LOGICAL_DNS
            dns_lookup_family: V4_ONLY
            lb_policy: ROUND_ROBIN
            hosts:
            - socket_address:
                address: xds
                port_value: 9000
