xds:
  address: xds
  port: 9000
  tenants: 1000
  routes: 100
  pumpInterval: 10
  domain: "bladedancer.dynu.net"

envoy:
  # Have to duplicate these
  xds:
    address: xds
    port: 9000
  # args:
  #   - -l
  #   - debug
  #   - -c
  #   - /config/envoy.yaml
  secretMounts:
    certs:
      mountPath: /certs
      secretName: default-tls
      defaultMode: 511 # TODO
  ports:
    n0:
      containerPort: 443
      protocol: TCP
  service:
    type: LoadBalancer
    ports:
      n0:
        port: 443
        protocol: TCP
    # annotations:
    #   external-dns.alpha.kubernetes.io/hostname: '*.envoy.six.moloko.apic-k8s.axwaytest.net.'
    #   service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Project=apicentral
    #   service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  templates:
    envoy.yaml: |-
      ## refs:
      ## - https://www.envoyproxy.io/docs/envoy/latest/start/start#quick-start-to-run-simple-example
      ## - https://raw.githubusercontent.com/envoyproxy/envoy/master/configs/google_com_proxy.v2.yaml
      admin:
        access_log_path: /dev/stdout
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9901
      node:
        id: shard-0
        cluster: service_xds
      static_resources:
        listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 443
          filter_chains:
          - filters:
            - name: envoy.http_connection_manager
              config:
                rds:
                  config_source:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        envoy_grpc:
                          cluster_name: "service_xds"
                  route_config_name: local_route
                access_log:
                - name: envoy.file_access_log
                  config:
                    path: /dev/stdout
                stat_prefix: ingress_http
                http_filters:
                - name: envoy.router
            tls_context:
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/certs/certificate"
                    private_key:
                      filename: "/certs/privateKey"
        clusters:
        - name: service_xds
          connect_timeout: 0.25s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          hosts:
          - socket_address:
              address: {{ .Values.xds.address }}
              port_value: {{ .Values.xds.port }}
        - name: web_service
          connect_timeout: 0.25s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          hosts:
            - socket_address:
                address: google.com
                port_value: 443
          tls_context:
            sni: www.google.com
