apiVersion: v1
kind: Service
metadata:
  name: authz
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ .Chart.Name }}-authz
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Chart.Name }}-authz
  ports:
  - name: grpc-authz
    protocol: TCP
    port: {{ .Values.authz.port }}
    targetPort: 20000
